name: CI

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        platform: [macOS-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Rust environment
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up cargo
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements-dev.txt .
      - name: Build release wheels
        run: |
          maturin build --release
      - name: Test
        run: |
          pip install iondrive --no-index --find-links target/wheels --force-reinstall
          pytest
      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheel-${{ matrix.platform }}
          path: target/wheels/

  build-manylinux:
    runs-on: ubuntu-latest
    container:
      image: konstin2/maturin:master
    steps:
      - name: Checkout
        uses: actions/checkout@v1  # v2 does not run in the image.
      - name: Set up Rust environment
        run: |
          rustup default 1.41.0
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements-dev.txt .
      - name: Build release wheels
        run: |
          maturin build --release
      - name: Test
        run: |
          pip install iondrive --no-index --find-links target/wheels --force-reinstall
          pytest
      - name: Upload wheels
        uses: actions/upload-artifact@v1  # v2 does not run in the image.
        with:
          name: wheel-manylinux
          path: target/wheels/
