name: CI

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Rust environment
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Set up rust-cargo
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install cffi maturin pytest ufoLib2 .
      - name: Build release wheels
        run: |
          maturin build --release
      - name: Test
        run: pytest
      - uses: actions/upload-artifact@v2
        name: upload-wheel
        with:
          name: wheel-${{ matrix.platform }}
          path: target/wheels/
