name: manylinux

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: konstin2/maturin:master
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: maturin-build
        run: |
          rustup default 1.41.0
          maturin build --release
      - uses: actions/upload-artifact@v2
        name: upload-wheel
        with:
          name: wheel-manylinux
          path: target/wheels/
